### ISSUE TITLE
Issues with RSID?

### ISSUE THREAD

**Issue by JEmlay** [Bakisha/STM32-SID-PLAYER#2]
Not sure if this is an issue with this project specifically or an issue with this other project:

https://github.com/texelec/ChristmasSID/issues/1

I'm to understand that project uses this player.  I discovered their project can't handle the RSID format.  Does that extend down to this project?  Or did something get borked between here and there?

**Comment by Bakisha** [comment]
Hi. You are right, ChristmasSID is expanded version of this project. But unfortunately, nor this, nor ChristmasSID, is not able to play  RSID type of sid files.

**Comment by JEmlay** [comment]
Thanks for the clarification.  Appreciate it!
